base_url = "https://www.ruancomelli.com/"
author = "Ruan Comelli"

theme = "linkita"

default_language = "en"
minify_html = false

title = "Ruan Comelli"
description = "Ruan Comelli's personal website"
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
	{ name = "authors", feed = true, paginate_by = 5 },
	{ name = "tags", feed = true, paginate_by = 5 },
]

output_dir = "docs/"

[languages.pt]
title = "Ruan Comelli"
description = "Website pessoal de Ruan Comelli"
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
	{ name = "authors", feed = true, paginate_by = 5 },
	{ name = "tags", feed = true, paginate_by = 5 },
]

[markdown]
highlight_code = true
extra_syntaxes_and_themes = []
highlight_theme = "dracula"

[extra]
math = true
mermaid = true
comment = true
title_separator = " | "
header_menu_name = "sample_header"
use_cdn = false
disable_default_favicon = false

[extra.footer]
since = 2025
license_url = "https://creativecommons.org/licenses/by-sa/4.0/"
copyright = "&copy; $YEAR Ruan Comelli &vert; [CC BY-SA 4.0]($LICENSE_URL)"

[extra.giscus]
repo = "ruancomelli/ruancomelli"
repo_id = "R_kgDOOGVRhA"
category = "Website comments"
category_id = "DIC_kwDOOGVRhM4Cochm"
mapping = "pathname"
strict = 1
reactions_enabled = 1
emit_metadata = 1
input_position = "bottom"
theme = "dark"
lang = "en"
loading = "lazy"

[extra.languages]

[extra.languages.en]
locale = "en_US"
date_format = "%F"
date_format_archive = "%Y-%m-%d"
taxonomy_list_description = "A map of all $NAME on this site. Start exploring!"
taxonomy_single_description = "Browse articles related to $NAME. Start exploring!"

[extra.languages.pt]
locale = "pt_BR"
date_format = "%F"
date_format_archive = "%Y-%m-%d"
taxonomy_list_description = "Veja todos os $NAME neste site!"
taxonomy_single_description = "Lista de páginas relacionadas com $NAME."
header_menu_name = "sample_header_pt"

[extra.menus]
sample_header = [
	{ url = "$BASE_URL/projects/", name = "Projects", names_i18n = "common_projects" },
	# { url = "$BASE_URL/archive/", name = "Archive", names_i18n = "common_archive" },
	{ url = "$BASE_URL/tags/", name = "Tags", names_i18n = "common_tags" },
	# { url = "$BASE_URL/about/", name = "About", names_i18n = "common_about" },
	# { url = "$BASE_URL/blog/", name = "Blog", names_i18n = "common_blog" },
]
sample_header_pt = [
	{ url = "$BASE_URL/projects/", name = "Projetos", names_i18n = "common_projects" },
	# { url = "$BASE_URL/archive/", name = "Arquivo", names_i18n = "common_archive" },
	{ url = "$BASE_URL/tags/", name = "Tags", names_i18n = "common_tags" },
	# { url = "$BASE_URL/about/", name = "Sobre", names_i18n = "common_about" },
	# { url = "$BASE_URL/blog/", name = "Blog", names_i18n = "common_blog" },
]

[extra.profiles]
[extra.profiles.ruancomelli]
name = "Ruan Comelli"
avatar_url = "images/profile-hero.jpg"
avatar_invert = false

[extra.profiles.ruancomelli.languages]
[extra.profiles.ruancomelli.languages.en]
bio = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
avatar_alt = "Demo profile avatar."
[extra.profiles.ruancomelli.languages.pt]
bio = "Um tema de blog limpo e elegante para Zola. Linkita é baseada em Kita e Hugo-Paper e é multilíngue e SEO-friendly."
avatar_alt = "Avatar de perfil de demonstração."

# TODO: Add open graph profile?
# [extra.profiles.ruancomelli.open_graph]
# first_name = "Ruan"
# last_name = "Comelli"
# username = "ruancomelli"
# gender = "male"
# image = "images/screenshot.png"
# # fb_app_id = ""
# # fb_admins = ["USER_ID"]
# [extra.profiles.ruancomelli.open_graph.fediverse_creator]
# handle = "bg.ruancomelli.eu"
# domain = "bsky.brid.gy"
# # Set url because I'm using bridge instead of a real mastodon account
# url = "https://bsky.brid.gy/ap/did:plc:3ebgy675tgwzqudufqvifpxv"
# [extra.profiles.ruancomelli.open_graph.languages]
# en = { image_alt = "Screenshot of this website." }
# pt = { image_alt = "Captura de tela deste site." }

[[extra.profiles.ruancomelli.social]]
name = "github"
url = "https://github.com/ruancomelli"
[[extra.profiles.ruancomelli.social]]
name = "home"
url = "https://ruancomelli.com/"
[extra.profiles.ruancomelli.social.urls]
pt = "https://ruancomelli.com/pt/"
[[extra.profiles.ruancomelli.social]]
name = "rss"
url = "$BASE_URL/authors/ruancomelli/atom.xml"
