# Configuration for the website

base_url = "https://www.ruancomelli.com"
title = "/home/ruancomelli"
description = "Ruan Comelli's personal website"
author = "Ruan Comelli"

# See https://welpo.github.io/tabi/blog/mastering-tabi-settings/
# for a complete documentation for the tabi theme
theme = "tabi"

build_search_index = true

generate_feeds = true
taxonomies = [
    { name = "tags", feed = true, paginate_by = 5 },
]

compile_sass = true
generate_sitemap = true
generate_robots_txt = true

default_language = "en"

[languages.pt]
title = "/home/ruancomelli"
description = "Website pessoal de Ruan Comelli"
build_search_index = true
generate_feeds = true
taxonomies = [
    { name = "tags", feed = true, paginate_by = 5 },
]

[markdown]
bottom_footnotes = true
highlight_code = true
highlight_theme = "dracula"
# extra_syntaxes_and_themes = []
external_links_class = "external"

[link_checker]
skip_prefixes = [
    # I don't know why, but my LinkedIn profile URL is flagged as invalid
    "https://www.linkedin.com/in/ruancomelli/",
]

[extra]
show_selected_language_code_in_language_switcher = true

use_cdn = true
comment = true
iine = true

favicon = "images/favicon.ico"

# See https://welpo.github.io/tabi/blog/mastering-tabi-settings/#social-media-cards
# Path to the fallback image for social media cards (the preview image shown when sharing a link on WhatsApp, LinkedIn…).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://github.com/welpo/tabi/pull/128
# TODO: automate link preview image generation with https://osc.garden/blog/automating-social-media-cards-zola/
social_media_card = "images/profile-hero.jpg"

# TODO: set this up when I have a Mastodon account - see https://welpo.github.io/tabi/blog/mastering-tabi-settings/#fediverse-creator
# fediverse_creator = { handle = "username", domain = "example.com" }

# display both the created and the updated dates
post_listing_date = "both"

# Projects
projects_path = "projects/_index.md"
# max_projects = 5
# show_projects_first = true

# the color theme
skin = "blue"

# Website source code
remote_repository_url = "https://github.com/ruancomelli/ruancomelli.github.io"
remote_repository_git_platform = "auto"
remote_repository_branch = "main"
show_remote_changes = true
show_remote_source = true

# ===============================
# Navigation
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#navigation
# ===============================
menu = [
    { name = "home", url = "/", trailing_slash = false },
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "bits", url = "bits", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "now", url = "now", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]
quick_navigation_buttons = true
toc = true
show_previous_next_article_links = true
invert_previous_next_article_links = true

# ===============================
# Usability
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#usability
# ===============================
copy_button = true
code_block_name_links = true
katex = true
mermaid = true

# ===============================
# Footer
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#footer
# ===============================
socials = [
    { name = "github", url = "https://github.com/ruancomelli/", icon = "github" },
    { name = "instagram", url = "https://instagram.com/ruancomelli", icon = "instagram" },
    { name = "youtube", url = "https://youtube.com/@ruancomelli", icon = "youtube" },
    { name = "spotify", url = "https://open.spotify.com/user/ruancomelli", icon = "spotify" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ruancomelli/", icon = "linkedin" },
]
feed_icon = true
footer_menu = [
    # { url = "about", name = "about", trailing_slash = true },
    # { url = "privacy", name = "privacy", trailing_slash = true },
    { url = "sitemap.xml", name = "Sitemap", trailing_slash = false },
    # { url = "https://example.com", name = "external link", trailing_slash = true },
]
copyright = "© $CURRENT_YEAR $AUTHOR $SEPARATOR Unless otherwise noted, the content in this website is available under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license."
copyright_translations.pt = "© $CURRENT_YEAR $AUTHOR $SEPARATOR A menos que se indique o contrário, o conteúdo deste site está disponível sob a licença [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

# ===============================
# Metadata
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#metadata
# ===============================
show_author = true
show_reading_time = true
show_date = true

# TODO: add a footer with a copyright and a license
# [extra.footer]
# since = 2025
# license_url = "https://creativecommons.org/licenses/by-sa/4.0/"
# copyright = "&copy; $YEAR Ruan Comelli &vert; [CC BY-SA 4.0]($LICENSE_URL)"
# site_repository = "https://github.com/ruancomelli/ruancomelli.github.io"

# TODO: update the repo_id, category_id values from https://giscus.app/
# See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#adding-comments
[extra.giscus]
enabled_for_all_posts = true  # Enables giscus on all posts. It can be enabled on individual posts by setting `giscus = true` in the [extra] section of a post's front matter.
automatic_loading = true  # If set to false, a "Load comments" button will be shown.
repo = "ruancomelli/ruancomelli.github.io"  # Your repository in format "owner/repo"
repo_id = "R_kgDOOILy4Q"
category = "Website comments"
category_id = "DIC_kwDOOILy4c4Ctvs3"
mapping = "pathname"  # Available: pathname; url; title; slug
strict_title_matching = 1  # 1 to enable, 0 to disable
enable_reactions = 1  # 1 to enable, 0 to disable
comment_box_above_comments = false
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""  # Leave blank to match the page's language
lazy_loading = true

# [extra.menus]
# sample_header = [
#     { url = "$BASE_URL/projects/", name = "Projects", names_i18n = "common_projects" },
#     # { url = "$BASE_URL/archive/", name = "Archive", names_i18n = "common_archive" },
#     # { url = "$BASE_URL/tags/", name = "Tags", names_i18n = "common_tags" },
#     { url = "$BASE_URL/about/", name = "About", names_i18n = "common_about" },
#     # { url = "$BASE_URL/blog/", name = "Blog", names_i18n = "common_blog" },
# ]
# sample_header_pt = [
#     { url = "$BASE_URL/projects/", name = "Projetos", names_i18n = "common_projects" },
#     # { url = "$BASE_URL/archive/", name = "Arquivo", names_i18n = "common_archive" },
#     # { url = "$BASE_URL/tags/", name = "Tags", names_i18n = "common_tags" },
#     { url = "$BASE_URL/about/", name = "Sobre", names_i18n = "common_about" },
#     # { url = "$BASE_URL/blog/", name = "Blog", names_i18n = "common_blog" },
# ]

# [extra.profiles]
# [extra.profiles.ruancomelli]
# name = "Ruan Comelli"
# avatar_url = "images/profile-hero.jpg"
# avatar_invert = false

# [extra.profiles.ruancomelli.languages]
# [extra.profiles.ruancomelli.languages.en]
# bio = "Software Engineer with a strong focus on AI, code quality, and developer tools. Currently exploring LLM-powered applications and automation. Master's in Mechanical Engineering, self-taught programmer, and open-source enthusiast."
# avatar_alt = "Demo profile avatar."
# [extra.profiles.ruancomelli.languages.pt]
# bio = "Engenheiro de Software com foco em IA, qualidade de código e ferramentas para desenvolvedores. Atualmente explorando aplicações baseadas em LLMs e automação. Mestre em Engenharia Mecânica, programador autodidata e entusiasta de código aberto."
# avatar_alt = "Avatar de perfil de demonstração."

# TODO: Add open graph profile?
# [extra.profiles.ruancomelli.open_graph]
# first_name = "Ruan"
# last_name = "Comelli"
# username = "ruancomelli"
# gender = "male"
# image = "images/screenshot.png"
# # fb_app_id = ""
# # fb_admins = ["USER_ID"]
# [extra.profiles.ruancomelli.open_graph.fediverse_creator]
# handle = "bg.ruancomelli.eu"
# domain = "bsky.brid.gy"
# # Set url because I'm using bridge instead of a real mastodon account
# url = "https://bsky.brid.gy/ap/did:plc:3ebgy675tgwzqudufqvifpxv"
# [extra.profiles.ruancomelli.open_graph.languages]
# en = { image_alt = "Screenshot of this website." }
# pt = { image_alt = "Captura de tela deste site." }

# [[extra.profiles.ruancomelli.social]]
# name = "home"
# url = "https://www.ruancomelli.com/"
# urls = { pt = "https://www.ruancomelli.com/pt" }
# [[extra.profiles.ruancomelli.social]]
# name = "github"
# url = "https://github.com/ruancomelli"
# [[extra.profiles.ruancomelli.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/ruancomelli/"
# urls = { pt = "https://www.linkedin.com/in/ruancomelli/?locale=pt_BR" }

# [[extra.profiles.ruancomelli.social]]
# name = "rss"
# url = "$BASE_URL/authors/ruancomelli/atom.xml"
